/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InstitucionalRouteImport } from './routes/institucional'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as AvisosRouteImport } from './routes/avisos'
import { Route as IndexRouteImport } from './routes/index'

const InstitucionalRoute = InstitucionalRouteImport.update({
  id: '/institucional',
  path: '/institucional',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosRoute = AvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avisos': typeof AvisosRoute
  '/calendario': typeof CalendarioRoute
  '/contacto': typeof ContactoRoute
  '/galeria': typeof GaleriaRoute
  '/institucional': typeof InstitucionalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avisos': typeof AvisosRoute
  '/calendario': typeof CalendarioRoute
  '/contacto': typeof ContactoRoute
  '/galeria': typeof GaleriaRoute
  '/institucional': typeof InstitucionalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avisos': typeof AvisosRoute
  '/calendario': typeof CalendarioRoute
  '/contacto': typeof ContactoRoute
  '/galeria': typeof GaleriaRoute
  '/institucional': typeof InstitucionalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avisos'
    | '/calendario'
    | '/contacto'
    | '/galeria'
    | '/institucional'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avisos'
    | '/calendario'
    | '/contacto'
    | '/galeria'
    | '/institucional'
  id:
    | '__root__'
    | '/'
    | '/avisos'
    | '/calendario'
    | '/contacto'
    | '/galeria'
    | '/institucional'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisosRoute: typeof AvisosRoute
  CalendarioRoute: typeof CalendarioRoute
  ContactoRoute: typeof ContactoRoute
  GaleriaRoute: typeof GaleriaRoute
  InstitucionalRoute: typeof InstitucionalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/institucional': {
      id: '/institucional'
      path: '/institucional'
      fullPath: '/institucional'
      preLoaderRoute: typeof InstitucionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos': {
      id: '/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisosRoute: AvisosRoute,
  CalendarioRoute: CalendarioRoute,
  ContactoRoute: ContactoRoute,
  GaleriaRoute: GaleriaRoute,
  InstitucionalRoute: InstitucionalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
